### ISSUE TITLE
integrate with AR find_or_create_by?

### ISSUE THREAD

**Issue by jrochkind** [seamusabshere/upsert#50]
In Rails4 (maybe previously?), AR has a find_or_create_by -- it has close to the same semantics as an upsert, but doesn't truly do an atomic upsert, it first does a select, then does an insert if neccessary. 

But it got me thinking if it would be possible to write true upsert func like this gem, but which enhanced the AR find_or_create_by instead of providing it's own API.   You would just write your code using standard AR API, but if you had the upsert gem installed _and_ you were using a database that upsert gem imported, you would get the true upsert implementation.  Otherwise, you would get standard AR functionality.  It would be almost the same semantics either way, the difference would be that since standard AR func isn't atomic it has the possibility of creating a duplicate (or violating a unique constraint), where true upsert doesn't. Plus different performance characteristics of course. 

If you later uninstalled the gem, it would go back to standard AR functionality. 

What do you think? Good idea? Feasible?

**Comment by jrochkind** [comment]
http://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by

**Comment by chetang** [comment]
:+1:

**Comment by pnomolos** [comment]
While it is unfortunate that `find_or_create_by` doesn't do an atomic operation, I don't believe it would be feasible for Upsert to interact with ActiveRecord at this level, due to the following reasons:
- Callbacks: AR fires different callbacks depending on whether a record is created or just saved.  We'd need to somehow track those records to be able to provide identical functionality, because AR's usual method of tracking this (whether or not a record has a primary key assigned) would no longer be valid.
- Returning the record information: Upsert doesn't return record information - it's a one-way operation to get your data into the database as fast as possible.  While it's _technically_ possible to get the information back out in the same query (or same chain of queries) you lose a lot of the performance benefits, so there would be a lot of extra work to provide just this functionality.

Ultimately I think this it is well outside the purpose of this library. An AR extension that uses the [pessimistic locking](http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html) API would probably be a much better fit.

**Comment by jrochkind** [comment]
Okay, thanks. I might hack on it myself a bit if I have time. Pessimistic locking is not a good fit for me.  I don't upsert on pk though, I let the db assign pk but upsert on another column. But getting the data back out from the upsert would be the real stumbling block, especially to get the pk as in my use case.

**Comment by pnomolos** [comment]
@jrochkind Yeah, unfortunately doing that as well as being compatible with the existing callback chain, etc, on `find_or_create_by` is going to be extremely tricky.  It sounds like you might be better off with something custom specifically for your purpose.  If you're using Postgres, you'll want to look into something like this: http://stackoverflow.com/questions/2276574/returning-inserted-rows-in-postgresql

With MySQL there's an SO example I found using a procedure to do roughly the same thing (don't have the link at the moment).  Sqlite requires using a cursor and multiple queries.

**Comment by jrochkind** [comment]
Aha, looks like someone's already done this for postgres and Rails5, probably using the postgres technique you mentioned, although I haven't read the source yet. 

https://github.com/jesjos/active_record_upsert
