### ISSUE TITLE
on postgresql, trying to put strings into integer fields fails confusingly

### ISSUE THREAD

**Issue by seamusabshere** [seamusabshere/upsert#7]
```
upsert(foo: 0)
```

if `foo` is a string field, it will blow up confusingly

**Comment by pnomolos** [comment]
@seamusabshere Do you want to catch this at the Upsert level (specifically check the types of the fields being inserted, which seems slow) or try to catch the exception from Postgres and turn it in to something useful?

**Comment by pnomolos** [comment]
I took a look and unfortunately `pg` doesn't let you register an error handler, which means we're going to need to wrap every upsert call in a `rescue` block ... which is going to introduce a slight bit of slowdown, although I'm not sure how much.

I think that rather than trying to present a useful error message we instead add a note to the README indicating that mis-matched types are going to result in cryptic error messages.

**Comment by seamusabshere** [comment]
@pnomolos i think you did the right thing
